name: pff-dev

services:
  minio:
    image: minio/minio:RELEASE.2024-05-10T01-41-38Z-cpuv1
    container_name: pigment-simulator-dev-minio
    command: [ "server", "/data", "--console-address", ":9001" ]
    environment:
      MINIO_ROOT_USER: ${PIGMENT_MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${PIGMENT_MINIO_ROOT_PASSWORD}
    volumes:
      - ${PIGMENT_MINIO_DATA}:/data