spring:
  llm:
    uri: gpt://b1gs02efi9ecn1ih2v9r/yandexgpt/latest
    oAuthToken: y0_AgAAAAAXLrNhAATuwQAAAAEaPIoxAABqS2O6cN1DF5PNS3DhknWVUMNXvg
  application:
    name: Product Feed Fixer
  datasource:
    url: jdbc:postgresql://localhost:5678/pff
    password: P0sTgR3SsS!
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
application:
  llm:
    coverage: 0.3