spring:
  config:
    import: "optional:configserver:"
  llm:
    uri: gpt://b1gs02efi9ecn1ih2v9r/yandexgpt/latest
    oAuthToken: y0_AgAAAAAXLrNhAATuwQAAAAEaPIoxAABqS2O6cN1DF5PNS3DhknWVUMNXvg
  application:
    name: Product Feed Fixer
  datasource:
    url: jdbc:postgresql://localhost:5432/pff
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 700MB
      max-request-size: 700MB
  cloud:
    config:
      enabled: false

logging:
  level:
    ru.roe.pff: DEBUG

minio:
  username: minioadmin
  password: minioadmin
  url: "http://localhost:9000"
  bucket-name: "pff-bucket"

application:
  llm:
    coverage: 0.3