spring:
  application:
    name: Product Feed Fixer
  datasource:
    url: jdbc:postgresql://localhost:5678/pff
    password: P0sTgR3SsS!
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect