spring:
  application:
    name: Product Feed Fixer
  datasource:
    url: jdbc:postgresql://localhost:5432/pff
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect