spring:
  application:
    name: Product Feed Fixer
  datasource:
    url: jdbc:postgresql://localhost:5432/pff
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 700MB
      max-request-size: 700MB

logging:
  level:
    ru.roe.pff: DEBUG

minio:
  username: minioadmin
  password: minioadmin
  url: "http://localhost:9000"
  bucket-name: "pff-bucket"